name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master
      - developer

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Extract branch name
        id: extract_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get last commit message and author
        id: last-commit
        run: |
          commit_message=$(git log -1 --pretty=%B)
          commit_author=$(git log -1 --pretty=%an)
          
          # Guardar en variables de entorno
          echo "commit_message=$commit_message" >> $GITHUB_ENV
          echo "commit_author=$commit_author" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ env.branch_name }}"
          destination_branch: "developer"
          pr_title: "${{ env.commit_author }}: ${{ env.commit_message }}"
          pr_body: "Este PR fue generado automáticamente para fusionar los cambios de `${{ env.branch_name }}` en `developer`."
          github_token: ${{ secrets.GITHUB_TOKEN }}