name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main
      - developer

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: developer
          title: "Auto PR: Merge ${{ github.ref_name }} into developer"
          body: "Este Pull Request fue generado automáticamente después de un push a `${{ github.ref_name }}`."
